server:
  port: 9000

security:
  jwt:
#    key-store: classpath:mykeystore.jks
#    key-store-password: pepojm
#    key-pair-alias: pepo
#    key-pair-password: pepojm
    key-store: classpath:keystorenew.jks
    key-store-password: qwerty
    key-pair-alias: josé maría martínez sánchez
    key-pair-password: qwerty

spring:
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      INDENT_OUTPUT: true
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
#    url: jdbc:mysql://eu-cdbr-west-03.cleardb.net/heroku_5a688b674e1c8ce?reconnect=true
    url: jdbc:h2:mem:testdb
#    username: b6fb8f90e775fa
#    password: f315f735
    username: sa
    password: sa
    initialization-mode: always
    driver-class-name: org.h2.Driver

logging:
  level:
    org.springframework.security: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE


