server:
  port: 9100

security:
  jwt:
    public-key: classpath:public.txt

spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true


logging:
  level:
    org.springframework.security: debug
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE
